### ISSUE TITLE
Not start 

### ISSUE THREAD

**Issue by HumanG33k** [kevinshen56714/SkyOffice#36]
Following the readme on devuan stable. 

```bash 


npm install && npm start
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@colyseus/core@0.14.24',
npm WARN EBADENGINE   required: { node: '>= 14.x' },
npm WARN EBADENGINE   current: { node: 'v12.22.5', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'colyseus@0.14.23',
npm WARN EBADENGINE   required: { node: '>= 14.x' },
npm WARN EBADENGINE   current: { node: 'v12.22.5', npm: '7.5.2' }
npm WARN EBADENGINE }

added 391 packages, and audited 392 packages in 22s

30 packages are looking for funding
  run `npm fund` for details

14 vulnerabilities (1 low, 12 moderate, 1 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

> skyoffice@1.0.0 start
> cd server && ts-node-dev --project tsconfig.server.json --respawn --transpile-only index.ts

[INFO] 12:02:20 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 3.9.10)
/home/skyoffice/SkyOffice/node_modules/@colyseus/core/build/Server.js:80
            this.transport.server?.on('error', (err) => reject(err));
                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._compile (/home/skyoffice/SkyOffice/node_modules/source-map-support/source-map-support.js:568:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-8008399677996612.js:114:20)
    at Object.nodeDevHook [as .js] (/home/skyoffice/SkyOffice/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
[ERROR] 12:02:20 SyntaxError: Unexpected token '.'
```

**Comment by kevinshen56714** [comment]
Seems like your need to upgrade your Node.js (`v12.22.5`) to later version (`>= v14.x`). Can you upgrade your Node and see if you still get the error?

**Comment by RicarteDeveloper** [comment]
Yes, it is the version of NODE. I have updated and it works fine.

**Comment by kevinshen56714** [comment]
Closing the issue as it's not a problem for Node version ```>= v14.x```.
