### ISSUE TITLE
Error with npm start

### ISSUE THREAD

**Issue by supafoundation** [kevinshen56714/SkyOffice#38]
index.js:1 Error: Class constructor Room cannot be invoked without 'new'
    at new MatchMakeError (Client.ts:12:1)
    at Client.<anonymous> (Client.ts:105:1)
    at step (tslib.es6.js:102:1)
    at Object.next (tslib.es6.js:83:1)
    at fulfilled (tslib.es6.js:73:1)
Unable to connect to room when using npm start. npm run build works fine

**Comment by kevinshen56714** [comment]
Did you run ```npm install``` prior to ```npm run start```?

**Comment by kevinshen56714** [comment]
Closing this as we have just done client side refactor. We are now using Vite as the build tool. Run `yarn && yarn dev` to start the client.
